# Example configuration file

# Full list of coin IDs can be found at https://docs.google.com/spreadsheets/d/1wTTuxXt8n9q7C4NDXqQpI3wpKu1_5bGVmP9Xz0XGSyU/edit?usp=sharing
coins:
  - polkadot
  - polkadex
  - astar
  - bitcoin
  - ethereum
  - tron
  - monero
  - kusama
  - rmrk
  - acala
  - solana
  - tether
  - cardano
  - binancecoin
  - crypto-com-chain

fiat-currency: usd